# PyTorch

## La librería PyTorch

Librería creada en 2016 por FAIR (Facebook AI Research) y liberada en 2018, basada en Torch, una librería de aprendizaje profundo en C++, pero centrada en Python. Desde su lanzamiento, PyTorch ha sido adoptado por una gran comunidad de investigadores y desarrolladores, llegando a competir (o incluso superar) a TensorFlow en muchos aspectos.

PyTorch destaca por su flexibilidad y lo pythonico (diseñado suguiendo los principios y [estilo de Python](https://peps.python.org/pep-0008/)) que es, lo que la hace más fácil de usar y de depurar que TensorFlow.


[![vs](img/pytorch_vs_tf.png)](https://github.com/diegoandradecanosa/CFR24/blob/main/slides/02_pytorchParte1P.pdf)


## Instalación

Para instalar pytorch, debemos seguir las [instrucciones de la página web](https://pytorch.org/get-started/locally/), donde nos permite configurar la versión de PyTorch (trabajaremos con la versión estable), el SO, el lenguaje (Python), y la plataforma hardware que se usará para computar.

Quien tenga una tarjeta gráfica NVIDIA, puede instalar la versión de PyTorch que incluye soporte para CUDA, lo que permite acelerar los cálculos en la GPU. 

PyTorch no incluye soporte nativo para tarjetas gráficas AMD, pero se puede instalar en linux la plataforma open-source [ROCm](https://pytorch.org/blog/pytorch-for-amd-rocm-platform-now-available-as-python-package/) para utilizarlas.

Por ejemplo, para crear un entorno de conda con PyTorch en un sistema Linux sin GPU, se pueden usar estos comandos:

```bash
conda create -n env_torch
conda activate env_torch
conda install pytorch torchvision torchaudio cpuonly -c pytorch
```

Podemos comprobar que ha sido correctamente instalada ejecutando la siguiente celda para importarla y ver la versión instalada.

In [1]:
import torch
print("Versión de Pytorch:",torch.__version__)
torch.cuda.is_available()

Versión de Pytorch: 2.3.0


True

## Tensores

Los tensores son la estructura de datos básica en PyTorch, y son similares a los arrays de NumPy, pero con algunas diferencias clave. En PyTorch, los tensores se pueden crear y manipular de forma eficiente en la GPU, lo que permite acelerar los cálculos en paralelo. Los tensores también son compatibles con la diferenciación automática, lo que permite calcular gradientes de forma eficiente para entrenar modelos de aprendizaje profundo.

Los tensores son útiles porque pueden representar muchos tipos diferentes de datos de una manera compacta y eficiente. Por ejemplo, una imagen se puede representar como un tensor 3D, donde las dos primeras dimensiones representan las filas y columnas de la imagen, y la tercera dimensión representa los canales de color (por ejemplo, rojo, verde, azul). De manera similar, un video se puede representar como un tensor 4D, donde las primeras tres dimensiones representan las filas, columnas y cuadros del video, y la cuarta dimensión representa los canales de color.

Los tensores también se usan ampliamente en el aprendizaje automático y el análisis de datos, donde se utilizan para representar las entradas y salidas de los modelos, así como los cálculos intermedios que se realizan sobre los datos.

[![tensores](img/tensors.png)](https://medium.com/@anoorasfatima/10-most-common-maths-operation-with-pytorchs-tensor-70a491d8cafd)

In [2]:
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]]) # Tensor a partir de una lista
print(t1) # Imprime el tensor
# no especifica el tipo porque infiere el por defecto para int (int64)
print(t1.dtype) # Tipo de los elementos (inferido)
print(t1.shape) # Forma del tensor (dimensiones)

tensor([[1, 2, 3],
        [4, 5, 6]])
torch.int64
torch.Size([2, 3])


In [3]:
import numpy as np
# Tensor de 1D a partir de un array de numpy
print(torch.from_numpy(np.array([1, 2, 3])))

tensor([1, 2, 3], dtype=torch.int32)


In [4]:
# PyTorch puede crear tensores con valores específicos del mismo modo que NumPy
print(torch.zeros(2, 2))
print(torch.ones(2, 2))
print(torch.rand(2, 2))

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.9086, 0.4982],
        [0.2959, 0.4498]])


In [5]:
torch.tensor([1, 2, 3], dtype=torch.float32) # Tensor especificando tipo float32 en lugar de inferirlo

tensor([1., 2., 3.])

In [6]:
t2 = torch.tensor([[1, 2], [3, 4], [5, 6]])

print(t1 + t1) # Suma elemento a elemento
print(t1 - t1) # Resta elemento a elemento
print(t1 * t1) # Multiplicación elemento a elemento
print(t1 / t1) # División elemento a elemento

tensor([[ 2,  4,  6],
        [ 8, 10, 12]])
tensor([[0, 0, 0],
        [0, 0, 0]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [7]:
print(t1.T) # Transpuesta de un tensor

print(torch.matmul(t1, t2)) # Producto matricial
print(t1 @ t2) # Producto matricial

tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[22, 28],
        [49, 64]])
tensor([[22, 28],
        [49, 64]])


In [8]:
print(t1[0]) # Primer elemento
print(t1[1, 1]) # Elemento en la fila 1, columna 1
print(t1[1:]) # Desde el segundo elemento en adelante
print(t1[1, :]) # Fila 1
print(t1[:, 1]) # Columna 1
print(t1[1, 1:]) # Fila 1, desde el segundo elemento en adelante
print(t1[1:, 1:]) # Submatriz


tensor([1, 2, 3])
tensor(5)
tensor([[4, 5, 6]])
tensor([4, 5, 6])
tensor([2, 5])
tensor([5, 6])
tensor([[5, 6]])


## Uso de GPGPU

En las últimas dos décadas, se ha venido utilizando el paralelismo de las GPUs para acelerar los cálculos en el aprendizaje profundo, en lo que se conoce como ***GPGPU*** (General-Purpose computing on Graphics Processing Units).

- [Xataka.com - Las GPU como pasado, presente y futuro de la computación](https://www.xataka.com/componentes/las-gpu-como-pasado-presente-y-futuro-de-la-computacion)
- [Dot CSV: ¿Por qué las GPUs son buenas para la IA? (con resumen acelerado de arquitectura de ordenadores)](https://www.youtube.com/watch?v=C_wSHKG8_fg)

Numpy no permite el uso de GPUs (aunque existen otras librerías específicas como [CuPy](https://cupy.dev/) para procesar arrays usando [CUDA](https://es.wikipedia.org/wiki/CUDA)). Sin embargo, las librerías de *deep learning*, como **PyTorch**, sí permiten el uso de GPUs para acelerar los cálculos. 

PyTorch permite nativamente usar GPUs de NVIDIA a través de la [CUDA](https://es.wikipedia.org/wiki/CUDA), así como las de Apple a través de [Metal](https://en.wikipedia.org/wiki/Metal_(API)). Las GPU de AMD se pueden utilizar a través de [ROCm](https://pytorch.org/blog/pytorch-for-amd-rocm-platform-now-available-as-python-package/).

Los tensores permiten definir dónde van a ser almacenados. De este modo, se puede indicar explícitamente que se desea almacenar un tensor en la GPU, lo que permite acelerar los cálculos.


In [2]:
aval_device = (
    "cuda" if torch.cuda.is_available() # CUDA: Compute Unified Device Architecture (NVIDIA)
    else "mps" if torch.backends.mps.is_available() # MPS: Metal Performance Shaders (Apple)
    #else "hip" if torch.hip.is_available() # HIP: Heterogeneous-compute Interface for Portability (AMD - ROCm)
    else "cpu" 
)

if aval_device == "cuda":
    print(f"GPU: {torch.cuda.get_device_name(0)} is available.")
elif aval_device == "mps":
    print("MPS is available.")
elif aval_device == "hip":
    print("HIP is available.")
else:
    print("No GPU available. Training will run on CPU.")

GPU: NVIDIA GeForce GTX 1650 is available.


En la siguiente celda, si se dispone de una GPU, se puede ver cómo PyTorch no permite realizar operaciones entre tensores que no están en el mismo dispositivo y cómo moverlos con el método `.to()`.

In [3]:
t1 = torch.tensor([[1., 2.], [3., 4.]], device="cpu") # Tensor en la CPU
print(t1.device)

if torch.cuda.is_available(): # Si hay GPU disponible
    
    t2 = torch.tensor([[1., 2., 3.], [4., 5., 6.]], device="cuda") # Tensor en la GPU
    
    try:
        print(torch.matmul(t1, t2)) # Error: no se pueden multiplicar tensores en diferentes dispositivos.
    except RuntimeError as e: 
        print("RuntimeError:", e)
        
    t1 = t1.to("cuda") # Movemos el tensor a la GPU
    print(torch.matmul(t1, t2)) # Multiplicando en la GPU
    
else:
    print("No tienes GPU para poder testear el código anterior.")

cpu
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument tensor in method wrapper_CUDA__dot)
tensor(14., device='cuda:0')


## Fuentes

- https://pytorch.org/docs/stable/tensors.html
- https://medium.com/@jayeshjain_246/what-are-tensors-495cf37c18e6
- https://medium.com/@anoorasfatima/10-most-common-maths-operation-with-pytorchs-tensor-70a491d8cafd